
INSERT INTO EMPLOYEE_REGISTRY (EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_AGE)
VALUES('Vishal Patil', 'TPS', 37);

INSERT INTO EMPLOYEE_REGISTRY (EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_AGE)
VALUES('Nitin Dawange', 'Nordea', 36);

INSERT INTO EMPLOYEE_REGISTRY (EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_AGE)
VALUES('Sumit Nikalje', 'Alfa', 32);
