DROP TABLE IF EXISTS EMPLOYEE_REGISTRY;

CREATE TABLE EMPLOYEE_REGISTRY(
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(50) NOT NULL,
    EMPLOYEE_DEPARTMENT VARCHAR(30) NOT NULL,
    EMPLOYEE_AGE INT NOT NULL
);